---
deployment:
  tasks:
    - export PATH=/opt/alt/alt-nodejs22/root/usr/bin:$PATH
    - cd /home/knjsnjuv/repositories/penjualan_frontend
    - npm ci
    - npm run build
    - /bin/rm -rf /home/knjsnjuv/public_html/assets
    - /bin/rm -f /home/knjsnjuv/public_html/index.html
    - /bin/cp -R dist/. /home/knjsnjuv/public_html/